# .github/workflows/bluesky-post.yml
name: Publish to Bluesky

on:
  schedule:
    - cron: '15 7 * * *' # 15 minut po spuštění Netlify buildu

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: node .github/scripts/bluesky-post.js
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
